### ISSUE TITLE
Can not work in Markdown code block

### ISSUE THREAD

**Issue by HackYardo** [JuliaEditorSupport/Julia-sublime#108]
If you type below in Sublime Text 4, "print" will turn color into blue 

\```java
print()
\```
However, below will not
\```julia
print()
\```

**Comment by stephenll** [comment]
This has nothing to do with the Julia Package.  The Markdown syntax in Sublime doesn't have a code fence for Julia.  

Add a Markdown.sublime-syntax file in your user directory with the following contents, then select the Markdown syntax under the User folder at the bottom right corner of the Sublime window.  

I think this only works under Sublime Text 4.  This is extending the Markdown syntax by using inheritance.

```yaml
%YAML 1.2
---
name: Markdown
file_extensions:
  - md
  - mdown
  - markdown
  - markdn
scope: text.html.markdown
extends: Packages/Markdown/Markdown.sublime-syntax

contexts:

  fenced-code-block:
    - meta_prepend: true
    - match: |-
             (?x)
              {{fenced_code_block_start}}
              ((?i:julia|jl))
              {{fenced_code_block_trailing_infostring_characters}}
      captures:
        0: meta.code-fence.definition.begin.julia.markdown-gfm
        2: punctuation.definition.raw.code-fence.begin.markdown
        5: constant.other.language-name.markdown
      embed: scope:source.julia
      embed_scope: markup.raw.code-fence.julia.markdown-gfm
      escape: '{{code_fence_escape}}'
      escape_captures:
        0: meta.code-fence.definition.end.julia.markdown-gfm
        1: punctuation.definition.raw.code-fence.end.markdown

```
