### ISSUE TITLE
Color macro calls?

### ISSUE THREAD

**Issue by musm** [JuliaEditorSupport/Julia-sublime#39]
Currently all macros are set in plain color for me. It would be nice if it had a prettier color default

**Comment by ViktorQvarfordt** [comment]
Macros should definitely be highlighted. Since you closed this I assume you got it working.

**Comment by musm** [comment]
Yeah I had to add it manually to my color scheme. It would be nice if it was by  default highlighted 👍

**Comment by ViktorQvarfordt** [comment]
Macro are highlighted by default in the default color theme. You must have been using something non-standard. If not, something is messed up and I shall try to fix it, please provide more information.

As can be seen in the `Julia.sublime-syntax` file (below), we set the scopes `support.function.julia` and `variable.macro.julia` for macro calls:

```
  macros:
    - match: '@{{symb_id}}+\b'
      # Julians want their macros to light up as functions by default
      # The scope `variable.macro` is applied last to give it precedence
      # so that user can override the color in the color theme.
      scope: support.function.julia variable.macro.julia
```

https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/Julia.sublime-syntax#L282
