### ISSUE TITLE
Documenter strings containing LATex are broken e.g. doc""" $ latex here $ """

### ISSUE THREAD

**Issue by Chunkulator** [JuliaEditorSupport/Julia-sublime#71]
Test case:
```julia
# LATex in Documenter strings
  doc"""$\pi$"""
# ^^^^^^^^^^^^^^ string.quoted.other

```
Patch:
```yaml
  strings:
    ...
    # Documenter string, tripple-quoted. Has special escaping and no string interpolation.
    - match: '\bdoc"""'
      push:
      - meta_scope: string.quoted.other.julia
      - match: (\\"|\\\\)
        scope: constant.character.escape.julia
      - match: '"""'
        pop: true

```
