### ISSUE TITLE
Compared to 0.9, 1.0.1 does not handle re-indentation correctly

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaEditorSupport/Julia-sublime#90]
For instance, this code is not re-indented correctly when I do "select all" and "reindent":
```
function e1_hole_q4()

    function solve(iteration, fens, fes)
     
        # Identify the "growth" layer of elements
        node_is_act_bdry = fill(false, count(fens))
        node_is_act_bdry[lopeningn] .= true
        el_in_growth_layer = fill(false, count(fes))
        for i in 1:count(fes)
            for j in fes.conn[i]
                if node_is_act_bdry[j]
                    el_in_growth_layer[i] = true
                    break
                end
            end
        end
        
# Apply mechanical support conditions to eliminate rigid body
# displacements
u = NodalField(zeros(size(fens.xyz, 1), 2)) # displacement field
setebc!(u, lleft0n, 1, 0.0)
setebc!(u, lleft0n, 2, 0.0)
setebc!(u, lright0n, 2, 0.0)
applyebc!(u)
numberdofs!(u)
end
end
```
ST3 with Julia-sublime package 0.9 can do it right.

**Comment by PetrKryslUCSD** [comment]
I was able to narrow it down quite a bit:
```
function f(x)
y = x^2 # comment
end

function f(x)
y = x^2 
end
```
In ST 4 the first definition of the function is not reinvented properly. ST 3 does the job correctly.

**Comment by PetrKryslUCSD** [comment]
It seems to me that being confused about scope could be an explanation.

**Comment by PetrKryslUCSD** [comment]
The problem is apparently in the definition of comments:
```
comments:
    - match: \#=
      scope: punctuation.definition.comment.number-equal-sign.julia
      push:
        - meta_scope: comment.block.number-equal-sign.julia
        - match: =\#
          scope: punctuation.definition.comment.number-equal-sign.julia
          pop: true
    - match: \#+
      scope: punctuation.definition.comment.julia
      push:
        - meta_scope: comment.line.number-sign.julia
        - match: \n
          pop: true
```
I replaced this with the old definition
```
  comments:
    - match: '#='
      push: comment-block
    - match: '#.*'
      scope: comment.line.number-sign.julia

  comment-block:
    - meta_scope: comment.block.number-sign-equals.julia
    - match: '#='
      push: comment-block
    - match: '=#'
      pop: true
```
and the re-indentation on ST 4 works as well as on ST3.
